"""Contract tests for the stable 1.x public convenience imports."""

from envs_xmpp_core import __version__
from envs_xmpp_core.runtime import (
    AlertTracker,
    CooldownDecision,
    DiagnosticError,
    HealthCheck,
    HealthSnapshot,
    KeyedCooldown,
    RoomJoinHealthState,
    SessionLifecycleSnapshot,
    SessionLifecycleState,
    TaskHealthState,
    TransitionAlertState,
    WatchdogHealthState,
    analyze_room_join_state,
    diagnostic_error,
    diagnostic_payload,
    exception_summary,
    health_check_from_messages,
    health_snapshot_messages,
    supervisor_task_health_state,
    watchdog_health_state,
)
from envs_xmpp_core.storage import (
    AsyncConnectionOutboxDatabase,
    OutboxCapacityError,
    OutboxMessage,
    OutboxStore,
    retry_delay_seconds,
)
from envs_xmpp_core.xmpp import (
    AffiliationQueryOptions,
    AffiliationQueryResult,
    AvatarPayload,
    MessageTarget,
    MessageTargetKind,
    MucJoinResult,
    MucOccupant,
    MucOccupantSnapshot,
    ReplyRoute,
    TaskLocalReplyRoute,
    avatar_sha1,
    await_muc_join_compat,
    cache_xep0153_hash,
    classify_message_target,
    find_occupant_by_jid,
    find_occupant_by_nick,
    find_self_occupant,
    iq_error_condition,
    iq_error_summary,
    iq_error_text,
    join_muc_confirmed,
    load_avatar_payload,
    normalize_affiliation,
    normalize_avatar_media_type,
    normalize_message_type,
    normalize_role,
    occupant_is_admin_or_owner,
    occupant_is_moderator,
    occupant_snapshot,
    publish_xep0084_avatar,
    query_muc_affiliation,
    set_presence_avatar_hash,
    start_muc_join_task,
    target_is_muc_room,
    wait_for_muc_self_presence,
    xmpp_strict_active,
)
from envs_xmpp_ops import (
    DeploymentProfile,
    DeploymentTarget,
    deployment_environment,
    resolve_environment_path,
    service_account,
    split_systemd_words,
    systemd_environment_value,
    systemd_exec_path,
    systemd_path_set,
    systemd_venv,
    venv_binary,
)


def test_distribution_version_is_1_1() -> None:
    assert __version__ == "1.1.0"


def test_stable_convenience_imports_are_exposed() -> None:
    exported = (
        AlertTracker,
        CooldownDecision,
        DiagnosticError,
        HealthCheck,
        HealthSnapshot,
        KeyedCooldown,
        RoomJoinHealthState,
        TaskHealthState,
        TransitionAlertState,
        WatchdogHealthState,
        analyze_room_join_state,
        SessionLifecycleSnapshot,
        SessionLifecycleState,
        diagnostic_error,
        diagnostic_payload,
        exception_summary,
        health_check_from_messages,
        health_snapshot_messages,
        supervisor_task_health_state,
        watchdog_health_state,
        AsyncConnectionOutboxDatabase,
        OutboxCapacityError,
        OutboxMessage,
        OutboxStore,
        retry_delay_seconds,
        AffiliationQueryOptions,
        AffiliationQueryResult,
        AvatarPayload,
        MessageTarget,
        MessageTargetKind,
        MucJoinResult,
        MucOccupant,
        MucOccupantSnapshot,
        ReplyRoute,
        TaskLocalReplyRoute,
        avatar_sha1,
        await_muc_join_compat,
        cache_xep0153_hash,
        classify_message_target,
        find_occupant_by_jid,
        find_occupant_by_nick,
        find_self_occupant,
        iq_error_condition,
        iq_error_summary,
        iq_error_text,
        iq_error_condition,
    iq_error_summary,
    iq_error_text,
    join_muc_confirmed,
        load_avatar_payload,
        normalize_affiliation,
        normalize_avatar_media_type,
        normalize_message_type,
        normalize_role,
        occupant_is_admin_or_owner,
        occupant_is_moderator,
        occupant_snapshot,
        publish_xep0084_avatar,
        query_muc_affiliation,
        set_presence_avatar_hash,
        start_muc_join_task,
        target_is_muc_room,
        wait_for_muc_self_presence,
        xmpp_strict_active,
        DeploymentProfile,
        DeploymentTarget,
        deployment_environment,
        resolve_environment_path,
        service_account,
        split_systemd_words,
        systemd_environment_value,
        systemd_exec_path,
        systemd_path_set,
        systemd_venv,
        venv_binary,
    )
    assert all(item is not None for item in exported)
